export const ENDPOINTS = {
  LOGIN: `app/login`,
  LOGOUT: `app/logout`,
  REGISTER: `public/register/user`,
  SKILL: `skill`,
  TOPIC: `topic`,
  EXAM: `exam`,
  SKILL_DELETE_MULTIPLE: `skill/delete/multiple`,
  TOPIC_DELETE_MULTIPLE: `topic/delete/multiple`,
  EXAM_DELETE_MULTIPLE: `exam/delete/multiple`,
  SKILL_HEADER: `skill/header`,
  TOPIC_EXAM: `topic/exam`,
  MINI_TEST_CARD: `mini-test`,
  EXAM_CARD: `exam/card`,
  VERIFY: `user/resetpassword/verify`,
  FORGOTPASS: `user/pwd/forgot`,
  RESETPASS: `user/pwd/reset`,
  CHANGEPASS: `user/changepassword`,
};
